/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const KeyShape = PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number,
]);

export const ReferenceBarShape = PropTypes.shape({
  boolField: PropTypes.bool,
});

export const ReferenceFooShape = PropTypes.shape({
  numberField: PropTypes.number,
  refField: ReferenceBarShape,
});

export const ArrayShapeObjectShape = PropTypes.shape({
  foo: PropTypes.string,
  bar: PropTypes.bool,
});

export const ArrayShape = PropTypes.shape({
  arrayField: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.string)),
  boolField: PropTypes.arrayOf(PropTypes.bool),
  enumField: PropTypes.arrayOf(PropTypes.oneOf([
    'FOO',
    'BAR',
    'BAZ',
    'QUX',
  ])),
  numberField: PropTypes.arrayOf(PropTypes.number),
  shapeField: PropTypes.arrayOf(ArrayShapeObjectShape),
  stringField: PropTypes.arrayOf(PropTypes.string),
  unionField: PropTypes.arrayOf(PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
  ])),
});

export const CoreFooShape = PropTypes.shape({
  id: KeyShape,
  name: PropTypes.string,
  foo: PropTypes.string,
});

export const CoreBarShape = PropTypes.shape({
  id: KeyShape,
  name: PropTypes.string,
  bar: PropTypes.number,
});

export const CoreShape = PropTypes.shape({
  id: KeyShape,
  name: PropTypes.string,
  foo: CoreFooShape,
  fooWithArg: CoreFooShape,
  bar: CoreBarShape,
  barWithArg: CoreBarShape,
});

export const EnumShape = PropTypes.shape({
  field: PropTypes.oneOf([
    'FOO',
    'BAR',
    'BAZ',
    'QUX',
  ]),
});

export const PrimitiveShape = PropTypes.shape({
  boolField: PropTypes.bool,
  boolFieldExpanded: PropTypes.bool,
  numberField: PropTypes.number,
  numberFieldExpanded: PropTypes.number,
  floatField: PropTypes.number,
  floatFieldExpanded: PropTypes.number,
  stringField: PropTypes.string,
  stringFieldExpanded: PropTypes.string,
});

export const ReferenceSelfShape = PropTypes.shape({
  stringField: PropTypes.string,
  referenceField: (...args) => ReferenceSelfShape(...args),
  requiredRefField: (...args) => ReferenceSelfShape(...args),
});

export const ReferenceShape = PropTypes.shape({
  stringField: PropTypes.string,
  refField: ReferenceFooShape,
  referenceField: ReferenceFooShape,
});

export const ShapeBasicStructShape = PropTypes.shape({
  foo: PropTypes.string,
});

export const ShapePrimitiveStructShape = PropTypes.shape({
  string: PropTypes.string,
  bool: PropTypes.bool,
  number: PropTypes.number,
});

export const ShapeArrayStructShape = PropTypes.shape({
  numberArray: PropTypes.arrayOf(PropTypes.number),
  stringArray: PropTypes.arrayOf(PropTypes.string),
  shapeArray: PropTypes.arrayOf(ShapeBasicStructShape),
});

export const ShapeEnumStructShape = PropTypes.shape({
  stringEnum: PropTypes.oneOf([
    'FOO',
    'BAR',
    'BAZ',
    'QUX',
  ]),
});

export const ShapeUnionStructShape = PropTypes.shape({
  multiUnion: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.bool,
    ShapeEnumStructShape,
  ]),
});

export const ShapeShape = PropTypes.shape({
  structAlias: ShapeBasicStructShape,
  primitiveFields: ShapePrimitiveStructShape,
  arrayFields: ShapeArrayStructShape,
  enumFields: ShapeEnumStructShape,
  unionFields: ShapeUnionStructShape,
});

export const UnionFooStructShape = PropTypes.shape({
  foo: PropTypes.string,
});

export const UnionBarStructShape = PropTypes.shape({
  bar: PropTypes.bool,
});

export const UnionBazStructShape = PropTypes.shape({
  baz: PropTypes.oneOfType([
    PropTypes.bool,
    PropTypes.number,
  ]),
});

export const UnionShape = PropTypes.shape({
  primitiveField: PropTypes.oneOfType([
    PropTypes.bool,
    PropTypes.number,
  ]),
  enumField: PropTypes.oneOfType([
    PropTypes.oneOf([
      'FOO',
      'BAR',
    ]),
    PropTypes.oneOf([
      'BAZ',
      'QUX',
    ]),
  ]),
  shapeField: PropTypes.oneOfType([
    UnionFooStructShape,
    UnionBarStructShape,
    UnionBazStructShape,
  ]),
  unionField: PropTypes.oneOfType([
    PropTypes.oneOfType([
      PropTypes.bool,
      PropTypes.number,
    ]),
    PropTypes.oneOfType([
      PropTypes.oneOf([
        'FOO',
        'BAR',
      ]),
      PropTypes.oneOf([
        'BAZ',
        'QUX',
      ]),
    ]),
    PropTypes.oneOfType([
      UnionFooStructShape,
      UnionBarStructShape,
      UnionBazStructShape,
    ]),
  ]),
});
