/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const PrimitiveShape = PropTypes.shape({
  boolField: PropTypes.bool,
  boolFieldExpanded: PropTypes.bool,
  numberField: PropTypes.number,
  numberFieldExpanded: PropTypes.number,
  floatField: PropTypes.number,
  floatFieldExpanded: PropTypes.number,
  stringField: PropTypes.string,
  stringFieldExpanded: PropTypes.string,
});
