/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const UnionFooStructShape = PropTypes.shape({
  foo: PropTypes.string,
});

export const UnionBarStructShape = PropTypes.shape({
  bar: PropTypes.bool,
});

export const UnionBazStructShape = PropTypes.shape({
  baz: PropTypes.oneOfType([
    PropTypes.bool.isRequired,
    PropTypes.number.isRequired,
  ]),
});

export const UnionShape = PropTypes.shape({
  primitiveField: PropTypes.oneOfType([
    PropTypes.bool.isRequired,
    PropTypes.number.isRequired,
  ]),
  enumField: PropTypes.oneOfType([
    PropTypes.oneOf([
      'FOO',
      'BAR',
    ]).isRequired,
    PropTypes.oneOf([
      'BAZ',
      'QUX',
    ]).isRequired,
  ]),
  shapeField: PropTypes.oneOfType([
    UnionFooStructShape.isRequired,
    UnionBarStructShape.isRequired,
    UnionBazStructShape.isRequired,
  ]),
  unionField: PropTypes.oneOfType([
    PropTypes.oneOfType([
      PropTypes.bool.isRequired,
      PropTypes.number.isRequired,
    ]).isRequired,
    PropTypes.oneOfType([
      PropTypes.oneOf([
        'FOO',
        'BAR',
      ]).isRequired,
      PropTypes.oneOf([
        'BAZ',
        'QUX',
      ]).isRequired,
    ]).isRequired,
    PropTypes.oneOfType([
      UnionFooStructShape.isRequired,
      UnionBarStructShape.isRequired,
      UnionBazStructShape.isRequired,
    ]).isRequired,
  ]),
});
