/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const UnsupportedNodesShape = PropTypes.shape({
  name: PropTypes.string,
});
