/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ShapeReferencePriceInterface {
  amount: number | null;
  nativeAmount: number | null;
  exchangeRate: number | null;
}

export interface ShapeReferenceInterface {
  fees: ShapeReferencePriceInterface | null;
  taxes: ShapeReferencePriceInterface;
  total: ShapeReferencePriceInterface;
}
