/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

export type CoreFooType = {
  id: number | string | null,
  name: ?string,
  foo: ?string,
};

export type CoreBarType = {
  id: number | string | null,
  name: ?string,
  bar: ?number,
};

export type CoreType = {
  id: number | string | null,
  name: ?string,
  foo: ?CoreFooType,
  fooWithArg: CoreFooType,
  bar: ?CoreBarType,
  barWithArg: CoreBarType,
};
