// Automatically generated by shapeshifter. Do not modify!
// @flow

export type ReferenceSelfType = {
  stringField: ?string,
  referenceField: ?ReferenceSelfType,
  requiredRefField: ReferenceSelfType,
};
