/* eslint-disable */
// Automatically generated by shapeshifter. Do not modify!
import DefaultName from '../stub';
import AnotherDefault, { Baz, Qux } from '../stub';

export interface ImportsInterface {
  stringField: string;
}
