/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface PolymorphVideoInterface {
  path: string | null;
}

export interface PolymorphImageInterface {
  url: string | null;
}

export interface PolymorphInterface {
  item: PolymorphImageInterface | PolymorphVideoInterface | null;
  item_id: string | number | null;
  item_type: string | null;
}
