/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ReferenceBarInterface {
  boolField: boolean | null;
}

export interface ReferenceSetOnlyStringInterface {
  stringField: string;
}

export interface ReferenceSetInterface {
  boolField: boolean;
  stringField: string;
  numberField: number;
}

export interface ReferenceFooInterface {
  numberField: number | null;
  refField: ReferenceBarInterface;
}

export interface ReferenceInterface {
  stringField: string;
  refField: ReferenceFooInterface;
  referenceField: ReferenceFooInterface;
  subsetRefField: ReferenceSetOnlyStringInterface;
}
