/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface SetsBasicInterface {
  foo: string;
  baz: boolean;
}

export interface SetsWithNullInterface {
  foo: string;
  qux: string;
}

export interface SetsInterface {
  foo: string;
  bar: number;
  baz: boolean;
  qux: string;
}
