/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface SetsBasicInterface {
  foo: string | null;
  baz: boolean;
}

export interface SetsWithNullInterface {
  foo: string;
  qux: string | null;
}

export interface SetsInterface {
  foo: string | null;
  bar: number | null;
  baz: boolean;
  qux: string;
}
