/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import UnionDefault, { UnionClassName } from '../stub';

export enum UnionEnumField0Enum {
  foo,
  bar,
  baz
}

export enum UnionEnumField1Enum {
  A = 789,
  B = 456,
  C = 123
}

export enum UnionUnionField01Enum {
  A = 1,
  B = 2,
  C = 3
}

export interface UnionInterface {
  arrayField: Array<string | null> | Array<{ [key: string]: string | null } | null> | null;
  primitiveFields: boolean | number | null;
  enumField: UnionEnumField0Enum | UnionEnumField1Enum | null;
  instanceField: UnionClassName | UnionDefault | null;
  objectField: { [key: string]: number | null } | { [key: string]: Array<string | null> | null } | null;
  shapeField: {
    foo: string | null;
    bar: boolean | null;
  } | {
    qux: string | boolean | null;
  } | null;
  unionField: string | UnionUnionField01Enum | boolean | number | null;
}
