/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

export type PrimitiveType = {
  boolField?: ?boolean,
  boolFieldExpanded?: boolean,
  numberField?: ?number,
  numberFieldExpanded?: number,
  floatField?: ?number,
  floatFieldExpanded?: number,
  stringField?: ?string,
  stringFieldExpanded?: string,
};
