/* eslint-disable */
// Automatically generated by shapeshifter. Do not modify!
export enum ArrayEnumFieldEnum {
  FOO,
  BAR,
  BAZ,
  QUX
}

export interface ArrayShapeObjectInterface {
  foo: string;
  bar: boolean;
}

export interface ArrayInterface {
  arrayField: Array<string[]>;
  boolField: boolean[];
  enumField: Array<ArrayEnumFieldEnum>;
  numberField: number[];
  shapeField: Array<ArrayShapeObjectInterface>;
  stringField: string[];
  unionField: Array<string | number>;
}
