/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface CoreFooInterface {
  id: number | string | null;
  name: string | null;
  foo: string | null;
}

export interface CoreBarInterface {
  id: number | string | null;
  name: string | null;
  bar: number | null;
}

export interface CoreInterface {
  id: number | string | null;
  name: string | null;
  foo: CoreFooInterface | null;
  fooWithArg: CoreFooInterface;
  bar: CoreBarInterface | null;
  barWithArg: CoreBarInterface;
}
