/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export enum EnumFieldEnum {
  FOO,
  BAR,
  BAZ,
  QUX
}

export interface EnumInterface {
  field: EnumFieldEnum;
}
