/* eslint-disable */
// Automatically generated by shapeshifter. Do not modify!
export interface PrimitiveInterface {
  boolField: boolean;
  boolFieldExpanded: boolean;
  numberField: number;
  numberFieldExpanded: number;
  floatField: number;
  floatFieldExpanded: number;
  stringField: string;
  stringFieldExpanded: string;
}
