/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ReferenceSelfInterface {
  stringField: string;
  referenceField: ReferenceSelfInterface;
  requiredRefField: ReferenceSelfInterface;
}
