/* eslint-disable */
// Automatically generated by shapeshifter. Do not modify!
export interface ReferenceSelfInterface {
  stringField: string;
  referenceField: ReferenceSelfInterface;
  requiredRefField: ReferenceSelfInterface;
}
