/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ReferenceSelfInterface {
  stringField: string | null;
  referenceField: ReferenceSelfInterface | null;
  requiredRefField: ReferenceSelfInterface;
}
