/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export enum UnionEnumField0Enum {
  FOO,
  BAR
}

export enum UnionEnumField1Enum {
  BAZ,
  QUX
}

export enum UnionUnionField10Enum {
  FOO,
  BAR
}

export enum UnionUnionField11Enum {
  BAZ,
  QUX
}

export interface UnionFooStructInterface {
  foo: string;
}

export interface UnionBarStructInterface {
  bar: boolean;
}

export interface UnionBazStructInterface {
  baz: boolean | number;
}

export interface UnionInterface {
  primitiveField: boolean | number;
  enumField: UnionEnumField0Enum | UnionEnumField1Enum;
  shapeField: UnionFooStructInterface | UnionBarStructInterface | UnionBazStructInterface;
  unionField: boolean | number | UnionUnionField10Enum | UnionUnionField11Enum | UnionFooStructInterface | UnionBarStructInterface | UnionBazStructInterface;
}
