enum ExampleEnum {
  FOO
  BAR
  BAZ
  QUX
}

type ShapeObject {
  foo: String
  bar: Boolean
}

union PrimitiveUnion = String | Int

type Array {
  arrayField: [[String]]
  boolField: [Boolean]
  enumField: [ExampleEnum]
  numberField: [Int]!
  shapeField: [ShapeObject]
  stringField: [String]
  unionField: [PrimitiveUnion!]
}
