type BasicStruct {
  foo: String
}

type PrimitiveStruct {
  string: String
  bool: Boolean!
  number: Number!
}

type ArrayStruct {
  numberArray: [Number]
  stringArray: [String]
  shapeArray: [BasicStruct]
}

enum ExampleEnum {
  FOO
  BAR
  BAZ
  QUX
}

type EnumStruct {
  stringEnum: ExampleEnum
}

union MultiUnion = Int | Boolean | EnumStruct

type UnionStruct {
  multiUnion: MultiUnion
}

type Shape {
  structAlias: BasicStruct
  primitiveFields: PrimitiveStruct
  arrayFields: ArrayStruct
  enumFields: EnumStruct
  unionFields: UnionStruct
}
