union PrimitiveUnion = Boolean | Int

enum FirstEnum {
  FOO
  BAR
}

enum SecondEnum {
  BAZ
  QUX
}

union EnumUnion = FirstEnum | SecondEnum

type FooStruct {
  foo: String
}

type BarStruct {
  bar: Boolean
}

type BazStruct {
  baz: PrimitiveUnion
}

union ShapeUnion = FooStruct | BarStruct | BazStruct

union ComplexUnion = PrimitiveUnion | EnumUnion | ShapeUnion

type Union {
  primitiveField: PrimitiveUnion
  enumField: EnumUnion
  shapeField: ShapeUnion
  unionField: ComplexUnion
}
