/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import ArrayDefault from '../stub';

export const ARRAY_NUM = 123;

export enum ArrayEnumFieldEnum {
  foo,
  bar,
  baz
}

export enum ArrayUnionField1Enum {
  A = 1,
  B = 2,
  C = 3
}

export interface ArrayInterface {
  arrayField?: Array<Array<string>>;
  boolField?: Array<boolean>;
  enumField?: Array<ArrayEnumFieldEnum>;
  instanceField?: Array<ArrayDefault>;
  numberField?: Array<number>;
  objectField?: Array<{ [key: string]: number }>;
  shapeField?: Array<{
    foo?: string;
    bar?: boolean;
  }>;
  stringField?: Array<string>;
  unionField?: Array<string | ArrayUnionField1Enum>;
}
