/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import ArrayDefault from '../stub';

export const ARRAY_NUM = 123;

export enum ArrayEnumFieldEnum {
  foo,
  bar,
  baz
}

export enum ArrayUnionField1Enum {
  A = 1,
  B = 2,
  C = 3
}

export interface ArrayInterface {
  arrayField: Array<Array<string | null> | null> | null;
  boolField: Array<boolean | null> | null;
  enumField: Array<ArrayEnumFieldEnum | null> | null;
  instanceField: Array<ArrayDefault | null> | null;
  numberField: Array<number | null>;
  objectField: Array<{ [key: string]: number | null } | null> | null;
  shapeField: Array<{
    foo: string | null;
    bar: boolean | null;
  } | null> | null;
  stringField: Array<string | null> | null;
  unionField: Array<string | ArrayUnionField1Enum | null> | null;
}
