/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import InstanceDefault, { InstanceClassName } from '../stub';

export const INST_STR = 'foobar';
export const INST_ENABLED = true;

export interface InstanceInterface {
  instField: InstanceClassName | null;
  instanceField: InstanceDefault;
}
