/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export const PRIMITIVE_VALUES = ['string', 123, true];
export const PRIMITIVE_STR = 'primitive';

export interface PrimitiveInterface {
  boolField?: boolean;
  boolFieldExpanded?: boolean | null;
  booleanField?: boolean;
  booleanFieldExpanded?: boolean | null;
  intField?: number;
  intFieldExpanded?: number | null;
  integerField?: number;
  integerFieldExpanded?: number | null;
  numField?: number;
  numFieldExpanded?: number | null;
  numberField?: number;
  numberFieldExpanded?: number | null;
  floatField?: number;
  floatFieldExpanded?: number | null;
  strField?: string;
  strFieldExpanded?: string | null;
  stringField?: string;
  stringFieldExpanded?: string | null;
}
