/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export const PRIMITIVE_VALUES = ['string', 123, true];
export const PRIMITIVE_STR = 'primitive';

export interface PrimitiveInterface {
  boolField: boolean | null;
  boolFieldExpanded: boolean;
  booleanField: boolean | null;
  booleanFieldExpanded: boolean;
  intField: number | null;
  intFieldExpanded: number;
  integerField: number | null;
  integerFieldExpanded: number;
  numField: number | null;
  numFieldExpanded: number;
  numberField: number | null;
  numberFieldExpanded: number;
  floatField: number | null;
  floatFieldExpanded: number;
  strField: string | null;
  strFieldExpanded: string;
  stringField: string | null;
  stringFieldExpanded: string;
}
