/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ReferenceBarInterface {
  boolField?: boolean;
}

export interface ReferenceSetOnlyStringInterface {
  stringField?: string;
}

export interface ReferenceSetInterface {
  boolField?: boolean;
  stringField?: string;
  numberField?: number;
}

export interface ReferenceFooInterface {
  numberField?: number;
  refField?: ReferenceBarInterface | null;
}

export interface ReferenceInterface {
  stringField?: string;
  refField?: ReferenceFooInterface | null;
  referenceField?: ReferenceFooInterface;
  subsetRefField?: ReferenceSetOnlyStringInterface;
}
