/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ReferenceSelfBasicInterface {
  stringField: string | null;
}

export interface ReferenceSelfInterface {
  stringField: string | null;
  referenceField: ReferenceSelfInterface | null;
  requiredRefField: ReferenceSelfInterface;
  subsetRefField: Array<ReferenceSelfBasicInterface | null> | null;
}
