/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface SetsBasicInterface {
  foo?: string;
  baz?: boolean | null;
}

export interface SetsWithNullInterface {
  foo?: string;
  qux?: string | null;
}

export interface SetsInterface {
  foo?: string;
  bar?: number;
  baz?: boolean | null;
  qux?: string | null;
}
