/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export interface ShapeReferencePriceInterface {
  amount?: number;
  nativeAmount?: number;
  exchangeRate?: number;
}

export interface ShapeReferenceInterface {
  fees?: ShapeReferencePriceInterface;
  taxes?: ShapeReferencePriceInterface;
  total?: ShapeReferencePriceInterface;
}
