/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import UnionDefault, { UnionClassName } from '../stub';

export enum UnionEnumField0Enum {
  foo,
  bar,
  baz
}

export enum UnionEnumField1Enum {
  A = 789,
  B = 456,
  C = 123
}

export enum UnionUnionField01Enum {
  A = 1,
  B = 2,
  C = 3
}

export interface UnionInterface {
  arrayField?: Array<string> | Array<{ [key: string]: string }>;
  primitiveFields?: boolean | number;
  enumField?: UnionEnumField0Enum | UnionEnumField1Enum;
  instanceField?: UnionClassName | UnionDefault;
  objectField?: { [key: string]: number } | { [key: string]: Array<string> };
  shapeField?: {
    foo?: string;
    bar?: boolean;
  } | {
    qux?: string | boolean;
  };
  unionField?: string | UnionUnionField01Enum | boolean | number;
}
