/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

import DefaultName from '../stub';
import AnotherDefault, { Baz, Qux } from '../stub';

export type ImportsType = {
  stringField?: string,
};
