/* eslint-disable */
// Automatically generated by shapeshifter. Do not modify!
// @flow
import Schema from 'some-other-schema-library';

export const MultipleChildrenSchema = new Schema('multiple-children', 'uuid');

export const SingleChildSchema = new Schema('single-child');

export const ParentSchema = new Schema('parents');

SingleChildSchema.hasOne({
  self: SingleChildSchema,
});

ParentSchema.hasOne({
  orphan: SingleChildSchema,
}).belongsToMany({
  children: MultipleChildrenSchema,
});
