/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

export type Key = string | number;

export type MultipleChildrenType = {
  uuid: ?string,
};

export type SingleChildType = {
  id: ?number,
  active: ?boolean,
  self: ?SingleChildType,
};

export type ParentType = {
  id: ?number,
  name: ?string,
  children: ?Array<?MultipleChildrenType>,
  orphan: ?SingleChildType,
  polymorph: SingleChildType | MultipleChildrenType | null,
  polymorph_fk: ?Key,
  polymorph_type: ?string,
};
