/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const PRIMITIVE_VALUES = ['string', 123, true];
export const PRIMITIVE_STR = 'primitive';

export const PrimitiveShape = PropTypes.shape({
  boolField: PropTypes.bool,
  boolFieldExpanded: PropTypes.bool,
  booleanField: PropTypes.bool,
  booleanFieldExpanded: PropTypes.bool,
  intField: PropTypes.number,
  intFieldExpanded: PropTypes.number,
  integerField: PropTypes.number,
  integerFieldExpanded: PropTypes.number,
  numField: PropTypes.number,
  numFieldExpanded: PropTypes.number,
  numberField: PropTypes.number,
  numberFieldExpanded: PropTypes.number,
  floatField: PropTypes.number,
  floatFieldExpanded: PropTypes.number,
  strField: PropTypes.string,
  strFieldExpanded: PropTypes.string,
  stringField: PropTypes.string,
  stringFieldExpanded: PropTypes.string,
});
