/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';

export const SetsBasicShape = PropTypes.shape({
  foo: PropTypes.string,
  baz: PropTypes.bool,
});

export const SetsWithNullShape = PropTypes.shape({
  foo: PropTypes.string,
  qux: PropTypes.string,
});

export const SetsShape = PropTypes.shape({
  foo: PropTypes.string,
  bar: PropTypes.number,
  baz: PropTypes.bool,
  qux: PropTypes.string,
});
