/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

export type Key = string | number;

export interface CoreFooInterface {
  id?: Key | null;
  name?: string | null;
  foo?: string | null;
}

export interface CoreBarInterface {
  id?: Key | null;
  name?: string | null;
  bar?: number | null;
}

export interface CoreInterface {
  id?: Key | null;
  name?: string | null;
  foo?: CoreFooInterface | null;
  fooWithArg?: CoreFooInterface;
  bar?: CoreBarInterface | null;
  barWithArg?: CoreBarInterface;
}
