/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import PropTypes from 'prop-types';
import Schema from 'shapeshifter';

export const Key = PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number,
]);

export type Key = string | number;

export const multipleChildrenSchema = new Schema('multiple-children', 'uuid');

export const singleChildSchema = new Schema('single-child');

export const parentSchema = new Schema('parents');

singleChildSchema
  .hasOne({
    self: singleChildSchema,
  });

parentSchema
  .morphTo({
    Single: singleChildSchema,
    'Model::Multiple': multipleChildrenSchema,
  }, 'polymorph', '_type', '_fk')
  .belongsToMany({
    children: multipleChildrenSchema,
  })
  .hasOne({
    orphan: singleChildSchema,
  });

export const MultipleChildren = PropTypes.shape({
  uuid: PropTypes.string,
});

export interface MultipleChildren {
  uuid?: string;
}

export const SingleChild = PropTypes.shape({
  id: PropTypes.number,
  active: PropTypes.bool,
  self: (...args) => SingleChild(...args),
});

export interface SingleChild {
  id?: number;
  active?: boolean;
  self?: SingleChild;
}

export const Parent = PropTypes.shape({
  id: PropTypes.number,
  name: PropTypes.string,
  children: PropTypes.arrayOf(MultipleChildren),
  orphan: SingleChild,
  polymorph: PropTypes.oneOfType([
    SingleChild,
    MultipleChildren,
  ]),
  polymorph_fk: Key,
  polymorph_type: PropTypes.string,
});

export interface Parent {
  id?: number;
  name?: string;
  children?: Array<MultipleChildren>;
  orphan?: SingleChild;
  polymorph?: SingleChild | MultipleChildren;
  polymorph_fk?: Key;
  polymorph_type?: string;
}
