/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */

import Schema from 'shapeshifter';

export type Key = string | number;

export const multipleChildrenSchema = new Schema<MultipleChildrenInterface>('multiple-children', 'uuid');

export const singleChildSchema = new Schema<SingleChildInterface>('single-child');

export const parentSchema = new Schema<ParentInterface>('parents');

singleChildSchema
  .hasOne({
    self: singleChildSchema,
  });

parentSchema
  .morphTo({
    Single: singleChildSchema,
    'Model::Multiple': multipleChildrenSchema,
  }, 'polymorph', '_type', '_fk')
  .belongsToMany({
    children: multipleChildrenSchema,
  })
  .hasOne({
    orphan: singleChildSchema,
  });

export interface MultipleChildrenInterface {
  uuid: string | null;
}

export interface SingleChildInterface {
  id: number | null;
  active: boolean | null;
  self: SingleChildInterface | null;
}

export interface ParentInterface {
  id: number | null;
  name: string | null;
  children: Array<MultipleChildrenInterface | null> | null;
  orphan: SingleChildInterface | null;
  polymorph: SingleChildInterface | MultipleChildrenInterface | null;
  polymorph_fk: Key | null;
  polymorph_type: string | null;
}
