/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

import ObjectDefault from '../stub';

export type ObjectType = {
  arrayField: ?{ [key: string]: ?Array<?string> },
  boolField: { [key: string]: ?boolean },
  enumField: { [key: string]: 'foo' | 'bar' | 'baz' },
  instanceField: ?{ [key: string]: ?ObjectDefault },
  numberField: ?{ [key: string]: ?number },
  objectField: ?{ [key: string]: ?{ [key: string]: ?number } },
  shapeField: ?{ [key: string]: ?{
    foo: ?string,
    bar: ?boolean,
  } },
  stringField: ?{ [key: string]: ?string },
  unionField: ?{ [key: string]: ?number | ?Array<?string> | null },
  objShorthandField: ?{ [key: string]: ?string },
  objKeyTypeField: ?{ [key: number]: ?string },
};
