/* Automatically generated by shapeshifter. Do not modify! */
/* eslint-disable */
/* @flow */

export type PolymorphVideoType = {
  path: ?string,
};

export type PolymorphImageType = {
  url: ?string,
};

export type PolymorphType = {
  item: PolymorphImageType | PolymorphVideoType | null,
  item_id: string | number | null,
  item_type: ?string,
};
